// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MitternachtsCupMVC.Data;

#nullable disable

namespace MitternachtsCupMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231108200057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MitternachtsCupMVC.Models.Ergebnis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PunkteTeamA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PunkteTeamB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpielId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpielId");

                    b.HasIndex("TeamId");

                    b.ToTable("Ergebnisse");
                });

            modelBuilder.Entity("MitternachtsCupMVC.Models.Spiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Platte")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("SpielDauer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartZeit")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("Spiele");
                });

            modelBuilder.Entity("MitternachtsCupMVC.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MitternachtsCupMVC.Models.Ergebnis", b =>
                {
                    b.HasOne("MitternachtsCupMVC.Models.Spiel", "Spiel")
                        .WithMany()
                        .HasForeignKey("SpielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MitternachtsCupMVC.Models.Team", "GewinnerTeam")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GewinnerTeam");

                    b.Navigation("Spiel");
                });

            modelBuilder.Entity("MitternachtsCupMVC.Models.Spiel", b =>
                {
                    b.HasOne("MitternachtsCupMVC.Models.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MitternachtsCupMVC.Models.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });
#pragma warning restore 612, 618
        }
    }
}
